byTorsten:
  React:
    autoInclude:
      'byTorsten.React': TRUE

Neos:
  Flow:
    mvc:
      routes:
        'byTorsten.React': TRUE
    log:
      reactLogger:
        logger: Neos\Flow\Log\Logger
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
           logFileURL: '%FLOW_PATH_DATA%Logs/React.log'
           createParentDirectories: TRUE
           severityThreshold: '%LOG_INFO%'
           maximumLogFileSize: 10485760
           logFilesToKeep: 1
           logMessageOrigin: FALSE
